=== magento/mtf/etc/variations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:redefine schemaLocation="../Magento/Mtf/Data/etc/types.xsd">
        <xs:complexType name="argumentType" mixed="false">
            <xs:complexContent>
                <xs:extension base="argumentType" />
            </xs:complexContent>
        </xs:complexType>
    </xs:redefine>

    <xs:element name="config">
        <xs:annotation>
            <xs:documentation>
                The root element for configuration data.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="testCase" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="testCase">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="variation" maxOccurs="unbounded" minOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains configuration data of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="xs:string" name="summary" use="required" />
            <xs:attribute type="xs:string" name="ticketId" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:element name="variation">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="data" type="argumentType" maxOccurs="unbounded" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains a single configuration data set of a test case variation.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
                <xs:element ref="constraint" maxOccurs="unbounded" minOccurs="0">
                    <xs:annotation>
                        <xs:documentation>
                            An element that contains a constraint className and order.
                        </xs:documentation>
                    </xs:annotation>
                </xs:element>
            </xs:choice>
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="xs:string" name="replace" use="optional" />
            <xs:attribute type="xs:string" name="firstConstraint" use="optional" />
            <xs:attribute type="xs:string" name="method" use="optional" />
            <xs:attribute type="xs:string" name="summary" use="optional" />
            <xs:attribute type="xs:string" name="ticketId" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:element name="constraint">
        <xs:complexType>
            <xs:attribute type="xs:string" name="name" use="required" />
            <xs:attribute type="xs:string" name="next" use="optional" />
            <xs:attribute type="xs:string" name="prev" use="optional" />
        </xs:complexType>
    </xs:element>
</xs:schema>

=== magento/mtf/tests/app/Magento/Tag/Test/TestCase/TagTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/variations.xsd">
  <testCase name="Magento\Tag\Test\TestCase\TagTest">
    <variation name="TagTestVariation1">
      <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
      <data name="fixture/data/strategy" xsi:type="string">css selector</data>
      <data name="fixture/data/search" xsi:type="string">variation priority:high</data>
      <data name="tag" xsi:type="string">priority:high</data>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityHigh"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityMiddle"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityLow"/>
    </variation>
    <variation name="TagTestVariation2">
      <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
      <data name="fixture/data/strategy" xsi:type="string">css selector</data>
      <data name="fixture/data/search" xsi:type="string">variation priority:middle</data>
      <data name="tag" xsi:type="string">priority:middle</data>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityHigh"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityMiddle"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityLow"/>
    </variation>
    <variation name="TagTestVariation3">
      <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
      <data name="fixture/data/strategy" xsi:type="string">css selector</data>
      <data name="fixture/data/search" xsi:type="string">variation priority:low</data>
      <data name="tag" xsi:type="string">priority:low</data>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityHigh"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityMiddle"/>
      <constraint name="Magento\Tag\Test\Constraint\TagSeverityLow"/>
    </variation>
  </testCase>
</config>

=== magento/mtf/tests/app/Magento/Mtf/Test/TestCase/InjectableTestCase.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/variations.xsd">
  <testCase name="Magento\Mtf\Test\TestCase\InjectableTestCase">
    <variation name="InjectableTestCaseVariation1" firstConstraint="pageOpenSuccess" method="test">
      <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
      <data name="fixture/data/strategy" xsi:type="string">css selector</data>
      <constraint name="Magento\Mtf\Test\Constraint\PageOpenSuccess"/>
    </variation>
    <variation name="InjectableTestCaseVariation2" firstConstraint="pageOpenSuccess" method="test">
      <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
      <data name="fixture/data/strategy" xsi:type="string">css selector</data>
      <data name="tag" xsi:type="string">success</data>
      <constraint name="Magento\Mtf\Test\Constraint\PageOpenSuccess"/>
    </variation>
  </testCase>
</config>

=== magento/mtf/tests/app/Magento/Mtf/Test/TestCase/InjectableTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/variations.xsd">
    <testCase name="Magento\Mtf\Test\TestCase\InjectableTest" summary="Test Injectable test case">
        <variation name="InjectableTestCaseVariation1" method="test1">
            <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
            <data name="fixture/data/strategy" xsi:type="string">css selector</data>
            <constraint name="Magento\Mtf\Test\Constraint\PageOpenSuccess" />
        </variation>
        <variation name="InjectableTestCaseVariation2" method="test1">
            <data name="fixture/data/locator" xsi:type="string">#hplogo</data>
            <data name="fixture/data/strategy" xsi:type="string">css selector</data>
            <data name="tag" xsi:type="string">success</data>
            <constraint name="Magento\Mtf\Test\Constraint\PageOpenSuccess" />
        </variation>
    </testCase>
</config>

=== magento/mtf/tests/app/Magento/BlockRender/Test/TestCase/BlockRenderTest.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
/**
 * Copyright Â© 2017 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
 -->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../etc/variations.xsd">
    <testCase name="Magento\BlockRender\Test\TestCase\BlockRenderTest" summary="Test Block render functionality">
        <variation name="InjectableTestCaseVariation1">
            <data name="blockRender/data/type" xsi:type="string">test</data>
            <data name="blockRender/data/search" xsi:type="string">Hello World!!!</data>
        </variation>
        <variation name="InjectableTestCaseVariation2">
            <data name="blockRender/data/type" xsi:type="string">render</data>
            <data name="blockRender/data/search" xsi:type="string">magento/mtf</data>
        </variation>
    </testCase>
</config>
